"""Feature lifecycle primitives shared by first-party and external features."""

from crew.features.dependencies import (
    FeatureActivationPlan,
    FeatureDependencyBlock,
    FeatureDependencyGraph,
    FeatureDependencyResolution,
    FeatureServiceDependencies,
)
from crew.features.manager import (
    FeatureDiagnostic,
    FeatureDefinition,
    FeatureInstallContext,
    FeatureRegistrationDiagnostic,
    FeatureRecord,
    FeatureRuntime,
    FeatureStartupAudit,
    MissingProvidedServicesError,
)
from crew.features.runtime import (
    FeatureActivationError,
    FeatureCleanupError,
    FeatureCleanupIssue,
    FeatureConfigRevisions,
    FeatureGeneration,
    FeatureScope,
    FeatureState,
    FeatureTransaction,
    RegistrationPhase,
    RegistrationState,
    RegistrationToken,
    StaleFeatureGenerationError,
)
from crew.features.services import (
    ServiceBinding,
    ServiceConflictError,
    ServiceKey,
    ServiceNotFoundError,
    ServiceRegistry,
    ServiceScopeKind,
    ServiceScopePath,
)

__all__ = [
    "FeatureActivationError",
    "FeatureActivationPlan",
    "FeatureCleanupError",
    "FeatureCleanupIssue",
    "FeatureConfigRevisions",
    "FeatureDependencyBlock",
    "FeatureDependencyGraph",
    "FeatureDependencyResolution",
    "FeatureDiagnostic",
    "FeatureDefinition",
    "FeatureGeneration",
    "FeatureInstallContext",
    "FeatureRecord",
    "FeatureRegistrationDiagnostic",
    "FeatureRuntime",
    "FeatureScope",
    "FeatureServiceDependencies",
    "FeatureState",
    "FeatureStartupAudit",
    "FeatureTransaction",
    "RegistrationPhase",
    "RegistrationState",
    "RegistrationToken",
    "MissingProvidedServicesError",
    "ServiceBinding",
    "ServiceConflictError",
    "ServiceKey",
    "ServiceNotFoundError",
    "ServiceRegistry",
    "ServiceScopeKind",
    "ServiceScopePath",
    "StaleFeatureGenerationError",
]
