#!/usr/bin/env python3
"""Build and stage the platform-native ACE security runtime."""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import shutil
import subprocess
from pathlib import Path


def source_hash(crate: Path) -> tuple[str, int]:
    """Hash the exact source set checked by the gateway stale-source guard."""
    files = sorted(
        path
        for path in (
            *crate.glob("src/**/*"),
            *crate.glob("tests/**/*.rs"),
            crate / "Cargo.toml",
            crate / "Cargo.lock",
        )
        if path.is_file()
    )
    digest = hashlib.sha256()
    for path in files:
        digest.update(path.relative_to(crate).as_posix().encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest(), len(files)


def default_target() -> str:
    """Return the release target for the host running this script."""
    system = platform.system()
    machine = platform.machine().lower()
    if system == "Darwin":
        return "aarch64-apple-darwin" if machine in {"arm64", "aarch64"} else "x86_64-apple-darwin"
    if system == "Windows":
        return "aarch64-pc-windows-msvc" if machine in {"arm64", "aarch64"} else "x86_64-pc-windows-msvc"
    if system == "Linux":
        return "aarch64-unknown-linux-gnu" if machine in {"arm64", "aarch64"} else "x86_64-unknown-linux-gnu"
    raise SystemExit(f"unsupported native runtime host: {system}/{platform.machine()}")


def binary_name(target: str) -> str:
    return "ace-security-runtime.exe" if "windows" in target else "ace-security-runtime"


def run_build(crate: Path, target: str) -> Path:
    command = [
        "cargo",
        "build",
        "--manifest-path",
        str(crate / "Cargo.toml"),
        "--release",
        "--locked",
        "--target",
        target,
    ]
    print("+", " ".join(command))
    subprocess.run(command, check=True)
    artifact = crate / "target" / target / "release" / binary_name(target)
    if not artifact.is_file():
        raise SystemExit(f"cargo completed but runtime artifact is missing: {artifact}")
    return artifact


def _previous_manifest(output: Path) -> dict:
    manifest_path = output / "runtime-manifest.json"
    if not manifest_path.is_file():
        return {}
    try:
        value = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def _previous_source_hash(manifest: dict, name: str) -> str:
    for item in manifest.get("files", []):
        if isinstance(item, dict) and item.get("name") == name:
            value = str(item.get("source_hash", "")).strip()
            if value:
                return value
    if manifest.get("binary_name") == name:
        return str(manifest.get("source_hash", "")).strip()
    return ""


def stage(crate: Path, artifact: Path, output: Path, target: str) -> Path:
    output.mkdir(parents=True, exist_ok=True)
    previous_manifest = _previous_manifest(output)
    name = artifact.name
    staged = output / name
    shutil.copy2(artifact, staged)
    if "windows" not in target:
        staged.chmod(staged.stat().st_mode | 0o111)

    digest = hashlib.sha256(staged.read_bytes()).hexdigest()
    source_digest, source_files = source_hash(crate)
    files = []
    for candidate_name in ("ace-security-runtime", "ace-security-runtime.exe"):
        candidate = output / candidate_name
        if not candidate.is_file():
            continue
        candidate_digest = hashlib.sha256(candidate.read_bytes()).hexdigest()
        candidate_source_hash = (
            source_digest
            if candidate_name == name
            else _previous_source_hash(previous_manifest, candidate_name)
        )
        entry = {
            "name": candidate_name,
            "sha256": candidate_digest,
            "size": candidate.stat().st_size,
        }
        if candidate_source_hash:
            entry["source_hash"] = candidate_source_hash
        files.append(entry)
    manifest = {
        "schema": 2,
        "runtime_version": "0.1.0",
        "platform": platform.system().lower(),
        "arch": platform.machine(),
        "generated_by": "security-runtime/scripts/build-security-runtime.py",
        "binary_name": name,
        "binary_sha256": digest,
        "source_hash": source_digest,
        "source_files": source_files,
        "built_for": target,
        "files": files,
        "note": "Generated by build-security-runtime.py; do not edit manually.",
    }
    manifest_path = output / "runtime-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"staged {staged}")
    print(f"manifest {manifest_path}")
    return staged


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default="", help="Rust target triple; defaults to the host")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "bin",
        help="directory receiving the runtime and manifest",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="stage an existing target/<triple>/release artifact",
    )
    args = parser.parse_args()

    crate = Path(__file__).resolve().parents[1]
    target = args.target or default_target()
    artifact = crate / "target" / target / "release" / binary_name(target)
    if not args.skip_build:
        artifact = run_build(crate, target)
    elif not artifact.is_file():
        raise SystemExit(f"--skip-build requested but artifact is missing: {artifact}")
    stage(crate, artifact, args.output.resolve(), target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
